services:
  shurl_db:
    image: postgres:18-alpine
    container_name: shurl_db
    environment:
      POSTGRES_DB: 'shurl'
      POSTGRES_USER: 'shurl'
      POSTGRES_PASSWORD: 'postgres'
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 35121:5432
    networks:
      - shurl_net

  shurl_redis:
    image: redis:8-alpine
    container_name: shurl_redis
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    environment:
      REDIS_PASSWORD: redis
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "redis"
    restart: unless-stopped
    networks:
      - shurl_net

  shurl_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shurl_app
    env_file: ./.env
    environment:
      - DATABASE_URL=postgres://shurl:postgres@shurl_db:5432/shurl
    ports:
      - 3007:3007
    networks:
      - shurl_net
    depends_on:
      - shurl_db
      - shurl_redis
    command:
      - /bin/sh
      - -c
      - |
        while ! nc -z shurl_db 5432; do
          sleep 1
        done
        npm run db:migrate && npm run start:prod

  otel_collector:
    image: otel/opentelemetry-collector:0.148.0
    container_name: otel_collector
    command: ["--config=/etc/otel-collector.yaml"]
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    ports:
      - "4317:4317" # gRPC
      - "4318:4318" # HTTP
    networks:
      - shurl_net
    depends_on:
      - tempo

  tempo:
    image: grafana/tempo:2.10.3
    container_name: tempo
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    ports:
      - "3200:3200"
    networks:
      - shurl_net

  grafana:
    image: grafana/grafana:12.4.1
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - shurl_net
    depends_on:
      - tempo
      - otel_collector

volumes:
  postgres-data:
  redis-data:

networks:
  shurl_net:
    name: shurl_net
