services:
  db_test:
    image: postgres:18-alpine
    container_name: db_test_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - '5432'

  redis_test:
    image: redis:8-alpine
    container_name: redis_test_db
    ports:
      - '6379'
